- name: variables
  hosts: localhost
  vars:  # Variable Declaration
    course: "Terraform"
    Trainer: "Siva"
    Duration: "120hrs"

  tasks:
  - name: print information
    vars: # Task level variables
      Course: "DevOps"
      trainer: "PHANI"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from {{Trainer}}, duration is {{Duration}}"
  - name: print information
    vars: # Task level variables
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from {{Trainer}}, duration is {{Duration}}"
